'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="DATA")>  _
Partial Public Class LNQ_OrderHistoryItemsDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.MassasrelliLabelPrinterLNQ.My.MySettings.Default.DATAConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property voeOrderHistoryItems() As System.Data.Linq.Table(Of voeOrderHistoryItem)
		Get
			Return Me.GetTable(Of voeOrderHistoryItem)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.voeOrderHistoryItem")>  _
Partial Public Class voeOrderHistoryItem
	
	Private _ord_no As String
	
	Private _qty_ordered As Decimal
	
	Private _item_no As String
	
	Private _pick_seq As String
	
	Private _item_desc_1 As String
	
	Private _cmt As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ord_no", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
	Public Property ord_no() As String
		Get
			Return Me._ord_no
		End Get
		Set
			If (String.Equals(Me._ord_no, value) = false) Then
				Me._ord_no = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_qty_ordered", DbType:="Decimal(13,4) NOT NULL")>  _
	Public Property qty_ordered() As Decimal
		Get
			Return Me._qty_ordered
		End Get
		Set
			If ((Me._qty_ordered = value)  _
						= false) Then
				Me._qty_ordered = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_item_no", DbType:="Char(15) NOT NULL", CanBeNull:=false)>  _
	Public Property item_no() As String
		Get
			Return Me._item_no
		End Get
		Set
			If (String.Equals(Me._item_no, value) = false) Then
				Me._item_no = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pick_seq", DbType:="VarChar(8)")>  _
	Public Property pick_seq() As String
		Get
			Return Me._pick_seq
		End Get
		Set
			If (String.Equals(Me._pick_seq, value) = false) Then
				Me._pick_seq = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_item_desc_1", DbType:="Char(30) NOT NULL", CanBeNull:=false)>  _
	Public Property item_desc_1() As String
		Get
			Return Me._item_desc_1
		End Get
		Set
			If (String.Equals(Me._item_desc_1, value) = false) Then
				Me._item_desc_1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cmt", DbType:="Char(40) NOT NULL", CanBeNull:=false)>  _
	Public Property cmt() As String
		Get
			Return Me._cmt
		End Get
		Set
			If (String.Equals(Me._cmt, value) = false) Then
				Me._cmt = value
			End If
		End Set
	End Property
End Class
