'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="DATA")>  _
Partial Public Class LNQ_OEORDEXTDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertOEORDEXT_MA(instance As OEORDEXT_MA)
    End Sub
  Partial Private Sub UpdateOEORDEXT_MA(instance As OEORDEXT_MA)
    End Sub
  Partial Private Sub DeleteOEORDEXT_MA(instance As OEORDEXT_MA)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.MassasrelliLabelPrinterLNQ.My.MySettings.Default.MassDATA_TCHPServerConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property OEORDEXT_MAs() As System.Data.Linq.Table(Of OEORDEXT_MA)
		Get
			Return Me.GetTable(Of OEORDEXT_MA)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.OEORDEXT_MAS")>  _
Partial Public Class OEORDEXT_MA
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ord_no As String
	
	Private _printed As System.Nullable(Of Integer)
	
	Private _uid As Integer
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Onord_noChanging(value As String)
    End Sub
    Partial Private Sub Onord_noChanged()
    End Sub
    Partial Private Sub OnprintedChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnprintedChanged()
    End Sub
    Partial Private Sub OnuidChanging(value As Integer)
    End Sub
    Partial Private Sub OnuidChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ord_no", DbType:="Char(8)")>  _
	Public Property ord_no() As String
		Get
			Return Me._ord_no
		End Get
		Set
			If (String.Equals(Me._ord_no, value) = false) Then
				Me.Onord_noChanging(value)
				Me.SendPropertyChanging
				Me._ord_no = value
				Me.SendPropertyChanged("ord_no")
				Me.Onord_noChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_printed", DbType:="Int")>  _
	Public Property printed() As System.Nullable(Of Integer)
		Get
			Return Me._printed
		End Get
		Set
			If (Me._printed.Equals(value) = false) Then
				Me.OnprintedChanging(value)
				Me.SendPropertyChanging
				Me._printed = value
				Me.SendPropertyChanged("printed")
				Me.OnprintedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_uid", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property uid() As Integer
		Get
			Return Me._uid
		End Get
		Set
			If ((Me._uid = value)  _
						= false) Then
				Me.OnuidChanging(value)
				Me.SendPropertyChanging
				Me._uid = value
				Me.SendPropertyChanged("uid")
				Me.OnuidChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
