'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="DATA")>  _
Partial Public Class LNQ_OrderListDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.MassasrelliLabelPrinterLNQ.My.MySettings.Default.DATAConnectionString1, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property voeGetOEOrdHdrLists() As System.Data.Linq.Table(Of voeGetOEOrdHdrList)
		Get
			Return Me.GetTable(Of voeGetOEOrdHdrList)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.voeGetOEOrdHdrList")>  _
Partial Public Class voeGetOEOrdHdrList
	
	Private _printed As String
	
	Private _ord_no As String
	
	Private _ord_dt As System.Nullable(Of Integer)
	
	Private _cus_no As String
	
	Private _cus_alt_adr_cd As String
	
	Private _bill_to_name As String
	
	Private _ship_to_name As String
	
	Private _status As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_printed", DbType:="NVarChar(1)")>  _
	Public Property printed() As String
		Get
			Return Me._printed
		End Get
		Set
			If (String.Equals(Me._printed, value) = false) Then
				Me._printed = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ord_no", DbType:="VarChar(12)")>  _
	Public Property ord_no() As String
		Get
			Return Me._ord_no
		End Get
		Set
			If (String.Equals(Me._ord_no, value) = false) Then
				Me._ord_no = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ord_dt", DbType:="Int")>  _
	Public Property ord_dt() As System.Nullable(Of Integer)
		Get
			Return Me._ord_dt
		End Get
		Set
			If (Me._ord_dt.Equals(value) = false) Then
				Me._ord_dt = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cus_no", DbType:="VarChar(12)")>  _
	Public Property cus_no() As String
		Get
			Return Me._cus_no
		End Get
		Set
			If (String.Equals(Me._cus_no, value) = false) Then
				Me._cus_no = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cus_alt_adr_cd", DbType:="VarChar(15)")>  _
	Public Property cus_alt_adr_cd() As String
		Get
			Return Me._cus_alt_adr_cd
		End Get
		Set
			If (String.Equals(Me._cus_alt_adr_cd, value) = false) Then
				Me._cus_alt_adr_cd = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_bill_to_name", DbType:="Char(40)")>  _
	Public Property bill_to_name() As String
		Get
			Return Me._bill_to_name
		End Get
		Set
			If (String.Equals(Me._bill_to_name, value) = false) Then
				Me._bill_to_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ship_to_name", DbType:="Char(40)")>  _
	Public Property ship_to_name() As String
		Get
			Return Me._ship_to_name
		End Get
		Set
			If (String.Equals(Me._ship_to_name, value) = false) Then
				Me._ship_to_name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_status", DbType:="VarChar(22) NOT NULL", CanBeNull:=false)>  _
	Public Property status() As String
		Get
			Return Me._status
		End Get
		Set
			If (String.Equals(Me._status, value) = false) Then
				Me._status = value
			End If
		End Set
	End Property
End Class
